sudo: required
services:
  - docker

before_install:
  - docker build -t romvic39/docker-react -f Dockerfile.dev .

script:
  - docker run romvic39/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region : "us-west-2"
  app:  "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-197942670379"
  bucket_path: "docker-react"
  access_key_id: 
      secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
      secure: "$AWS_SECRET_KEY"
